### ISSUE TITLE
Detect change in range slider

### ISSUE THREAD

**Issue by diegoaguilar** [seiyria/angular-bootstrap-slider#104]
When using a range slider, I want to get which, either start or end has changed. I'm trying to bind events or use a `$watch`  but it's getting buggy to know which is the one being changed:

Using a `$watch` this is what I try:

	$scope.$watch('rangeSlider.value', function (newValue,oldValue) {
		var changed = newValue[0] === oldValue[0] ? newValue[1] : newValue[0];
                ....
                ....
	});

But as I say, it's not reliable. Would you suggest any alternative?

**Comment by seiyria** [comment]
This isn't really a case that's covered by this particular library. This would be  a request that you would probably want to send upstream to bootstrap-slider, as you could just watch for an event then.

Closing as this isn't really an issue that can be taken care of here.

**Comment by diegoaguilar** [comment]
Ok, I understand. Any suggestion, so far?

**Comment by seiyria** [comment]
No, I don't really have any idea how to do this currently, but as far as I can tell this is definitely something that would have to be implemented upstream.
