### ISSUE TITLE
Formatter renders the function itself

### ISSUE THREAD

**Issue by sovattha** [seiyria/angular-bootstrap-slider#108]
If you have a formatter on one slider, it does not get rendered anymore, but instead you see the function contents!
Regression identified, I create a fix that I tested on my side...

**Comment by phyzalis** [comment]
Thank you for this

**Comment by sovattha** [comment]
You're welcome. I hope the issue will be fixed or merged soon.

**Comment by phyzalis** [comment]
It is still not working ...
