### ISSUE TITLE
How to reset price filter 

### ISSUE THREAD

**Issue by navin10sharma** [seiyria/angular-bootstrap-slider#110]
Hello guys

In jquery i used this method priceArray = mySlider.refresh();
  and it working fine but but in angular i have ng-model="multipleDemo.sliderValue"  so i try to empty this model with ng-click event $scope.multipleDemo.sliderValue = {}; But it throw some error...
![error](https://cloud.githubusercontent.com/assets/3096611/11299123/21f0dc22-8faa-11e5-9a18-a47f4455c3ee.png)

**Comment by seiyria** [comment]
Please provide a plunker or something for a demo.

Also, values have to be numeric - setting it to an object will not work, and throws the error expected.

**Comment by navin10sharma** [comment]
Hi thanks for your quick response..

You can open this URL http://ec2-52-32-72-182.us-west-2.compute.amazonaws.com:3000/   and just select the any price range and try to click on Clear Search Button  and u can see that error in  console....i try to clear the slider with ng-click and once we click i try to reset the ng-model value but it through error....i try lots and spend lots time but still not able to fix...

**Comment by seiyria** [comment]
In the future, please provide a _minimum_ reproducible case.

As I stated earlier, you cannot set this to an object. The value is not an object. In this case, it's an array of 2 numbers, so you need to set it to [0, 20000] or it won't work as you expect.
