### ISSUE TITLE
Update the README

### ISSUE THREAD

**Issue by sriprabha** [seiyria/angular-bootstrap-slider#118]
Can we update the documentation text `<slider ng-model="sliders.sliderValue" onSlideStop="myCallback($event,value)"></slider>`  to reflect the correct event name `on-stop-slide` as mentioned in the pull request [here](https://github.com/seiyria/angular-bootstrap-slider/pull/61)

**Comment by seiyria** [comment]
done, thanks!

**Comment by sriprabha** [comment]
:+1:
