### ISSUE TITLE
Make slider inline?

### ISSUE THREAD

**Issue by amacfie** [seiyria/angular-bootstrap-slider#125]
Is there a way to display the slider inline instead of as a block? 
The output of this:

    Label text: <slider style="display: inline;" ng-model="..."></slider>

is "Label text:" on a line above the slider. I'd like to get "Label text:" right before the slider on the same line.

**Comment by seiyria** [comment]
Set custom css for `.slider` to have `display: inline`.

**Comment by amacfie** [comment]
Thanks seiyria but that doesn't seem to be the solution http://jsfiddle.net/amacfie/e9hLLh6n/7/ ?

**Comment by seiyria** [comment]
That's because they also have width: 100% set on them. You should put them in separate containers like so (rough pseudocode):

```html
<div width=30%>Slider: </div>
<div width="70%"><slider /></div>
```
