### ISSUE TITLE
Bootstrap tabs tooltip issue

### ISSUE THREAD

**Issue by rajaramtt** [seiyria/angular-bootstrap-slider#153]
I used Bootstrap3 and angular-bootstrap-slider, tab1 working as expected but tab2 is not tooltip placement issue. could you please help me on this issue.

![selection_001](https://user-images.githubusercontent.com/17231665/29967118-aeb0497a-8f32-11e7-8df5-55272e161593.png)

**Comment by seiyria** [comment]
Call slider refresh when the tab changes.
