### ISSUE TITLE
Support angular 1.3.x

### ISSUE THREAD

**Issue by pencilcheck** [seiyria/angular-bootstrap-slider#31]

**Comment by evillemez** [comment]
It is in fact broken in 1.3.11 - not sure about other versions in the 1.3 line.  PR incoming.

**Comment by evillemez** [comment]
See #43

**Comment by pencilcheck** [comment]
Thanks

**Comment by poliveira89** [comment]
I came here because of this! :) Thanks for the update.

If you don't mind, could you update `bower.json` as well? At this moment, I still get the "warning" with the 1.3.x versions
