### ISSUE TITLE
Disabling the slider via scope variable

### ISSUE THREAD

**Issue by AviFix** [seiyria/angular-bootstrap-slider#32]
Hi,

is there a way to disable / enable the slider (read only) via scope variable?

Thank's
Avi

**Comment by davidjrme** [comment]
Hi,

The ng-disabled attribute is read at init but not by $scope.$watch after. The result is I can't enable or disable a slider dynamically.

If it can help, my dependencies:
```javascript
"dependencies": {
    "jquery": "~2.1.3",
    "ng-lodash": "~0.2.0",
    "angular": "~1.3.14",
    "angular-bootstrap": "~0.12.1",
    "bootstrap": "~3.3.2",
    "angular-google-maps": "~2.0.16",
    "seiyria-bootstrap-slider": "~4.5.7",
    "angular-bootstrap-slider": "~0.1.1"
  },
```

Thanks,
