### ISSUE TITLE
Tick Labels does not render

### ISSUE THREAD

**Issue by poliveira89** [seiyria/angular-bootstrap-slider#44]
Tried to use this slider on Angular as you sugges on this page:
````html
<slider ng-model="sliders.sliderValue" min="testOptions.min" step="testOptions.step" max="testOptions.max" value="testOptions.value"></slider>
````
But, mine differ a little bit, I need to have labels so, using options from [Bootstrap Slider](http://seiyria.github.io/bootstrap-slider/), like this: `data-slider-ticks-labels="['$0', '$100', '$200', '$300', '$400']"`, but this does not work properly...

In my case I have tried:
````html
<slider ng-model="stuff" ng-click="doSomething('value')" min="0" step="0.5" max="5" slider-ticks-labels="['0', '0.5', '1.0', '1.5', '2.0', '2.5', '3.0', '3.5', '4.0', '4.5', '5.0']"></slider>

<slider ng-model="stuff" ng-click="doSomething('value')" min="0" step="0.5" max="5" ticks-labels="['0', '0.5', '1.0', '1.5', '2.0', '2.5', '3.0', '3.5', '4.0', '4.5', '5.0']"></slider>
````
None of the above works, and the slider stays like this:
![image](https://cloud.githubusercontent.com/assets/1919475/6266231/b3e77004-b82e-11e4-89f0-e93533d58698.png)

**Comment by seiyria** [comment]
This library has not yet updated to support the latest features of bootstrap slider (tick labels, logarithmic scale, and others) as they were added quite recently. That said, I would love a PR!

**Comment by oliverjesse** [comment]
We tried just updating the dependency to 4.4.2 and got some interesting errors. Will try to work through them ... any big things you knew were going to break?

**Comment by seiyria** [comment]
tick marks for sure. it looks like logarithmic was not yet merged. there were also a ton of general fixes as far as I can see. what sorts of problems are you getting?

**Comment by punxcat** [comment]
@seiyria sorry to comment on this issue even though it is closed but - I'm having the same issue - is the tick labels still not a feature that is working as part of the angular version of this bootstrap slider? Thanks in advance..

**Comment by seiyria** [comment]
I'm not sure. I don't use this anymore.
