### ISSUE TITLE
setting the tooltip while using slider as an element

### ISSUE THREAD

**Issue by wpk5ew** [seiyria/angular-bootstrap-slider#49]
I am using the following code when creating this slider as an element.  

< slider id="uniqueID" ng-model="value" value="yearMin" min="1" step="1" max="10" ng-change="myfunction(value)" >
< /slider >

When I include tooltip="hide" as one of the html attributes, I am getting the following error: https://docs.angularjs.org/error/$compile/multidir?p0=slider&p1=tooltip&p2=new%2Fisolated%20scope&p3=%3Cdiv%20tooltip%3D%22hide%22%20id%3D%22yearSlider%7B%7Bdhmsmdeploymentmaptools.containerClass%7D%7D%22%20ng-model%3D%22yearValue%22%20value%3D%22yearMin%22%20min%3D%22yearMin%22%20step%3D%22hop%22%20max%3D%22yearMax%22%20ng-change%3D%22broadcastControl(%27updateYear%27,%20yearValue)%22%3E

Is there a different way I should be setting the tooltip hide/show value?

**Comment by seiyria** [comment]
This means you can't use two directives on the same div. in this case, it means you have a tooltip directive available (possibly from angular-ui) that's also being bound and that's causing the problem. I don't really have a workaround, but maybe setting data-tooltip will work? Or pass it in through an options object instead (I think this can be done).

**Comment by wpk5ew** [comment]
I appreciate the quick response!  I ended up passing the value in through an options object and all looks to be working properly.

Thanks!

**Comment by seiyria** [comment]
Great, glad to hear it's working for you.

**Comment by peterpuzos** [comment]
This may be a stupid question but how exactly did you pass the value through with an options object? I'm having the same issue with the conflict and I want to set tooltip to always.  There's no examples in the test code of passing through a set of options.  Just wondering what the proper way is to do it.
