### ISSUE TITLE
Slider not updating when slider value change

### ISSUE THREAD

**Issue by warapitiya** [seiyria/angular-bootstrap-slider#50]
Hi,

I'm trying to implement a autoplay function and trying to change the slider when "slider value" changes.
```javascript
$scope.test = function () {
            setInterval(function () {
                $scope.slider.value += 1;
                console.log('Count : ' + $scope.slider.value);
            }, 1000);
        };
```

when i try this, it's not moving my slider according to the slider value.

**Comment by seiyria** [comment]
Can you give me a plunk to look at?
