### ISSUE TITLE
scale option is taking length of the array instead of value in the array

### ISSUE THREAD

**Issue by kanagukrs** [seiyria/angular-bootstrap-slider#51]
As I give scale values in array, it takes the array length for positioning, and array values as label. It may be an issue or enhancement, we need to give value and custom label in the array as an object, and we may use that value for positioning the label

Ex:- SCALE - [{val:5, label:"low"}, {val:10, label:"medium"}, {val:15, label:"high"}]

**Comment by seiyria** [comment]
I think you were thinking of tick positions and such. Scale doesn't even take an array.
