### ISSUE TITLE
Doesn't work with v4.8.1

### ISSUE THREAD

**Issue by thisispaul** [seiyria/angular-bootstrap-slider#52]
What version of bootstrap-slider does this correlate to.

It seems like this is completely broken with the new version `v4.8.1`.

Firstly I get an error on line 101 saying that constrructor doesnt exist. I can fix that by making it lowercase `constructor`.

Then I get an issue with `_applyToFixedAndParseFloat` in bootstrap-slider, I think because I am using it as a range and sometimes the `num` getting passed in is an array from the looks of it. so `toFixed` doesn't exist as a function.

Can you recommend a version of bootstrap slider that this will work with or help me with what needs changing (even if its vague)?

Cheers

**Comment by thisispaul** [comment]
Just seen in your test that its using `3.1.0`. Is that the latest version this supports?

**Comment by seiyria** [comment]
It only supports whatever the bower.json is updated to support. If you need newer features, I'd appreciate a PR here!

**Comment by thisispaul** [comment]
Okay. I'm currently looking into it! Its a bit behind the versions so so might take a while!

**Comment by seiyria** [comment]
That's totally ok. Unfortunately, I'm probably in no better of a position than you. When you have something, definitely feel free to let me know.

**Comment by thisispaul** [comment]
Okay. I figured out whats going on actually.

If I add `range="true"` to to the slider then it works normally now. Weird as it was working before without that, it it worth adding some sort of autodetection for that based on the value passed in?

Its weird though, https://github.com/seiyria/bootstrap-slider seems to suggest that if the value is array then it will default to range is true but that doesnt seem to be happening.

Also, I find it strange that I need to pass in a value and ng-model. Are these not essentially the same thing? Or is there a use case for them being separate?

**Comment by seiyria** [comment]
To be honest, I don't quite know. There was a PR recently that re-wrote a lot of the logic in the directive. I checked it out, it seemed to work, and I didn't think much more of it then. Perhaps, value is the start value while ngModel is the value to bind to, though I can't see that making much sense. I think the author was going for a 1:1 parity between the original and the directive here.

**Comment by thisispaul** [comment]
Yeah. Looking at the past pull requests.

https://github.com/seiyria/angular-bootstrap-slider/commit/293a66fe1709888061d9d9211cd6baf86e5b7a5f

This seems to fix the initial `Constructor` problem and then https://github.com/seiyria/angular-bootstrap-slider/commit/3743d652c94d7980fd35d39266e568aea7dbcc70 reintroduces it again. 

I might send a pull reuqest for that initially and update the tests to the latest version of the bootstrap slider.

I could then maybe add a fallback for value to ngModel if value is empty. Rather than removing it completely, and can easily add a check if the value is an array and set range to true.

But don't need to do that as I can do that in my app rather than the plugin.

**Comment by seiyria** [comment]
That sounds fine to me. Thank you!

If you think it would be more convenient here (it sounds like it would be), I have no objections to it being a part of the plugin instead of something you have to set.

**Comment by thisispaul** [comment]
I've added a pull request. I havent done any of the fallback stuff yet as I couldn't get it working for now and I need to go out so will look at doing that later.

**Comment by seiyria** [comment]
Updated thanks to #39.
