### ISSUE TITLE
precision is not working inside tooltip

### ISSUE THREAD

**Issue by sarsarahman** [seiyria/angular-bootstrap-slider#54]
precision is not working inside tooltip? what for precision is used? how to control the precision inside tooltip.

**Comment by seiyria** [comment]
The tooltip uses the `formatter` function.

**Comment by sarsarahman** [comment]
I tried this and still its not affecting into tool tip. what could have went wrong?

<span slider slider-id="rangeSlider1" ng-model="val" scale="linear" formatter="formatterFn(val)" range="true" handle="custom" min="min" max="max" step="1" tooltipseparator="|" tooltipsplit="false" > </span>

   $scope.formatterFn = function(value) {
        console.log(value);
        value[0]=value[0].toFixed(2);
        value[1]=value[1].toFixed(2);
        return value;
    };

**Comment by seiyria** [comment]
Please make a plunk so I can see what you're doing.

**Comment by lukaszgrolik** [comment]
I had the same problem with "formatter" option - it works when `formatter="formatterFn"` (pass function, not the value returned by the function).
