### ISSUE TITLE
Coloring the low and high track segments.

### ISSUE THREAD

**Issue by aljamala** [seiyria/angular-bootstrap-slider#55]
In the slider for bootstrap examples (http://seiyria.github.io/bootstrap-slider/), they color the low/high tracks and selections with the following CSS.  However, this is the markup that is rendered when using this directive, where there is no slider-track-low and slider-track-high?

    <div class="slider-track">
      <div class="slider-selection" style="left: 35%; width: 30%;"></div>
      <div class="slider-handle round" style="left: 35%;"></div>
      <div class="slider-handle round" style="left: 65%;"></div>
    </div>

    #slider12a .slider-track-high, #slider12c .slider-track-high {
	  background: green;
    }

    #slider12b .slider-track-low, #slider12c .slider-track-low {
	   background: red;
    }

    #slider12c .slider-selection {
	   background: yellow;
    }

**Comment by seiyria** [comment]
It's quite possible this directive is not using the latest version of the slider, so it may be lagging behind in features.

**Comment by aljamala** [comment]
Yeah. looks like its using bootstrap-slider v3.1.0 which is way behind the current version of 4.8.1.  Any idea on when an update may come around?

**Comment by aljamala** [comment]
That does appear to be the case, v 3.1.0 is listed in the bower.json which is way behind the current version of 4.8.1.  Any idea if an update to the directive is coming soon?

**Comment by seiyria** [comment]
I do not have one planned; if you submit a PR, though, I'll probably take it!

**Comment by aljamala** [comment]
Great! Just want to make sure this PR isn't asking for the same thing?

https://github.com/seiyria/angular-bootstrap-slider/pull/39

**Comment by seiyria** [comment]
It is, but IIRC it was unable to merge so it didn't get accepted. I am not sure why I didn't comment on it though.

**Comment by aljamala** [comment]
Is it really as simple as updating the dependency version?  I tried this on my local box and not surprisingly it led to an error in slider.js

TypeError: Cannot read property 'prototype' of undefined
    at initSlider (http://localhost:53704/Scripts/lib/angular-bootstrap-slider/slider.js:101:48)
    at link (http://localhost:53704/Scripts/lib/angular-bootstrap-slider/slider.js:24:17)

**Comment by seiyria** [comment]
Of course, I have my suspicions it's not really that simple. That's why it's not done yet :P

**Comment by aljamala** [comment]
Haha, I figured! :)

Looks like the correct changes were made in this commit: https://github.com/seiyria/angular-bootstrap-slider/commit/d253c602c317d69a605eb21d2cb1a26a0ccc08de

However, when I try 

bower install angular-bootstrap-slider --save

I end up with version 0.0.6?  Am I missing something here?

**Comment by seiyria** [comment]
It's possible bower is being crappy. I sometimes have this problem as well. What if you try `bower install --save angular-bootstrap-slider#0.1.1`?

**Comment by aljamala** [comment]
I unfortunately already tried this, output looks correct, but not bower.json.  I do notice that the correct versions are in .bower.json but not bower.json

bower cached        git://github.com/seiyria/angular-bootstrap-slider.git#0.1.1
bower validate      0.1.1 against git://github.com/seiyria/angular-bootstrap-slider

**Comment by seiyria** [comment]
Hm. In that case, I'm really not sure. Have you tried clearing the local directory and trying again? Maybe `bower info angular-bootstrap-slider` would help identify what's up?

**Comment by aljamala** [comment]
Yeah, I tried uninstalling and re-installing with specific version and force latest.  I do see the correct version referenced in my main bower.json

    "angular-bootstrap-slider": "0.1.1"

but not in the angular-bootstrap-slider bower.json as I already mentioned.

**Comment by seiyria** [comment]
That's definitely strange; I'm sorry, I don't know if I have the knowledge to help you further.

**Comment by aljamala** [comment]
Yes, it is, and looking at the JS it definitely looks like the old version not the one in the commit mentioned above.  I'll keep digging I guess.

**Comment by seiyria** [comment]
We've got an update now, as of #39. Feel free to let me know if that fixes it for you.

**Comment by aljamala** [comment]
I'm almost sure that these updates would fix my issue, but I am still having a problem where bower keeps getting version 0.0.6 which relies on the older version of the bootstrap slider.  I've tried uninstalling, clearing cache, reinstalling but nothing has helped yet.

**Comment by aljamala** [comment]
I noticed that it downloads from https://github.com/seiyria/angular-bootstrap-slider/archive/0.1.1.tar.gz

and when I try to download from there manually this is the bower.json I see?
    {
  "name": "angular-bootstrap-slider",
  "version": "0.0.6",
  "authors": [
    "Kyle Kemp <kyle@seiyria.com>"
  ],
  "description": "An angular directive for seiyria-bootstrap-slider",
  "main": "slider.js",
  "keywords": [
    "angular",
    "slider",
    "bootstrap-slider",
    "bootstrap"
  ],
  "license": "MIT",
  "homepage": "http://seiyria.github.io/bootstrap-slider/",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ],
  "dependencies": {
    "seiyria-bootstrap-slider": "~3.1.0",
    "angular": "~1.2.16"
  }
}

**Comment by seiyria** [comment]
it's possible it's a caching issue then? maybe flush your dns, etc?

**Comment by aljamala** [comment]
I don't think so, I've tried flushing the dns cache as well as using a completely different machine that I don't use for development to download at that URL.  Same result.

**Comment by aljamala** [comment]
Can you please provide assistance on this version issue? I am fairly certain that the problem isn't from my end.  Would you be able to tag a new commit with a 0.1.2 tag? I cannot rely on having to download the zip from master.

https://github.com/seiyria/angular-bootstrap-slider/tags

**Comment by seiyria** [comment]
I've pushed 0.1.2. Unfortunately you've exhausted my knowledge on how to debug this but if this doesn't work and you have more ideas I'd be open to trying them.

**Comment by aljamala** [comment]
Yes, this did indeed fix the issue, now anyone using bower should be able to get the latest version. I do notice that precision is now required to be specified though? I had to set precision="0" on all my sliders; otherwise, _applyToFixedAndParseFloat function in bootstrap-slider.js throws an error.

**Comment by seiyria** [comment]
That's possible, sorry, if you want to submit a PR to set it by default, that'd be fine! Surprising that bootstrap-slider wouldn't have a sensible default though; I think something weird is happening there.

Anyway, I'm going to close this issue since it works now. Thanks! Sorry it took so long to resolve.
