### ISSUE TITLE
Attribute tooltip in conflict

### ISSUE THREAD

**Issue by hmillet** [seiyria/angular-bootstrap-slider#58]
I would like to hide tooltips on my slider.

So, I use the "tooltip" option that I set to "hide".

The result is, cause of an other angular directive for my tooltips, that I've got a global "hide" tooltip on my slider.

![2015-05-17 23_23_23-demo - opera](https://cloud.githubusercontent.com/assets/2003913/7672255/ceab49e0-fceb-11e4-8c54-a18eb3054826.png)

Nice isn't it ;-)

What about that ?

I can see one easy solution :
* have an alias to the "tooltip" attribute, like "slider-tooltip" (easy, I can make a PR)

What do you think about it ?

**Comment by seiyria** [comment]
Sure, feel free to make a PR!

**Comment by hmillet** [comment]
Result is correct
