### ISSUE TITLE
no such method 'setValue' for slider widget instance

### ISSUE THREAD

**Issue by namwkim** [seiyria/angular-bootstrap-slider#67]
I am also getting this issue. It seems related with recent updates? It was working fine before.

**Comment by namwkim** [comment]
in the following: 

// deregister ngModel watcher to prevent memory leaks
                        if (angular.isFunction(ngModelDeregisterFn)) ngModelDeregisterFn();
                        ngModelDeregisterFn = $scope.$watch('ngModel', function (value) {
                            slider.slider('setValue', value);
                        }, true);

**Comment by seiyria** [comment]
please post in the other issue, there's no need to have a duplicate.
