### ISSUE TITLE
use of the formatter

### ISSUE THREAD

**Issue by dirkjan111** [seiyria/angular-bootstrap-slider#79]
Hi,

Thanks for working on this directive.

Could you tell me if the formatter is working and if so how? I want to adjust the texts in the tooltips and judging from the documentation of the bootstrap slider project the formatter is the thing i should be using.

Please tell me how to apply the formatter in the context of this angular implementation.

Best,

Dirk

**Comment by seiyria** [comment]
```
$scope.formatter = function(value) { return 'test' + value; }
```

```
<slider formatter="formatter">
```

**Comment by dirkjan111** [comment]
Applying that appears to break my sliders.
<img width="1188" alt="screen shot 2015-07-09 at 18 52 04" src="https://cloud.githubusercontent.com/assets/881181/8601311/a143fb56-266b-11e5-8bdf-926904978eb4.png">
<img width="1214" alt="screen shot 2015-07-09 at 18 51 48" src="https://cloud.githubusercontent.com/assets/881181/8601312/a167d9d6-266b-11e5-905f-aeced7e82f6f.png">

**Comment by dirkjan111** [comment]
top one is with formatter applied, below without

**Comment by seiyria** [comment]
I would need a plunker to be able to see what you're doing.

**Comment by dirkjan111** [comment]
http://plnkr.co/edit/WaFy9V6ld6rxLt1KaVO8?p=preview

**Comment by seiyria** [comment]
While I can't figure out why the formatter doesn't actually work correctly, it's not breaking in the fashion that you're showing me in the screenshot above.

**Comment by dirkjan111** [comment]
You are right .... i placed a comma after the formatter initially, so i was about to apologize, then i saw this error...

**Comment by dirkjan111** [comment]
In my application it breaks different as in the plunker, attached my screenshot, perhaps it will provide a clue:
<img width="2395" alt="screen shot 2015-07-09 at 19 19 56" src="https://cloud.githubusercontent.com/assets/881181/8601908/9d7672ca-266f-11e5-8be4-36752dd7acf3.png">

**Comment by seiyria** [comment]
Sorry, not really, that could be anything in the stack (angular, bootstrap-slider, or the angular directive). Definitely not something I've seen before. Maybe it's a version mismatch of sorts.

**Comment by dirkjan111** [comment]
it's only after i add formatter="formatter" to the directive, strange thing is that i found this plunker in the closed issues: http://plnkr.co/edit/gAnhDTP98K8rpcW09UgC?p=preview, where it seems to be working fine

**Comment by seiyria** [comment]
Right, but I have no idea what version any of that is unfortunately, so who knows what versions any of those are?

**Comment by dirkjan111** [comment]
If it is working in my plunker (http://plnkr.co/edit/WaFy9V6ld6rxLt1KaVO8?p=preview) i will be able to get it working in my app
