### ISSUE TITLE
Implement `tooltip_split` and `tooltip_position`

### ISSUE THREAD

**Issue by marcules** [seiyria/angular-bootstrap-slider#87]
Attributes `tooltip_split` and `tooltip_position` set on the slider element should work like defined in https://github.com/seiyria/bootstrap-slider#options

**Comment by seiyria** [comment]
Supposedly these are already implemented, see [here](https://github.com/seiyria/angular-bootstrap-slider/blob/master/slider.js#L67) and [here](https://github.com/seiyria/angular-bootstrap-slider/blob/master/slider.js#L54) respectively. What you want is the `tooltipsplit` and `slider-tooltip-position` attribute.

**Comment by marcules** [comment]
I'm sorry, I didn't actually look in the code, and assumed they would be named like in the other project.  
Nevertheless I have a strange behaviour setting slider-tooltip-position to "bottom" with tooltipsplit set to true, see attached image.  Should I open a new issue for that? Or is it something specific to my platform?  
![image](https://cloud.githubusercontent.com/assets/2453108/8967573/07681814-3638-11e5-97c5-804977ee4786.png)

**Comment by seiyria** [comment]
Don't worry about it.

It's likely an issue that exists on bootstrap-slider -- please check there before opening a new one. If one exists, feel free to comment on it.
