### ISSUE TITLE
slide events not passing values?

### ISSUE THREAD

**Issue by aljamala** [seiyria/angular-bootstrap-slider#88]
I recently upgraded to v 0.1.17 and noticed that the new value from the slider is never passed in?

 on-start-slide="onSlideHandler(value, $event)"

When I debug it hits the handler but value is the same everytime and $event is undefined?

**Comment by seiyria** [comment]
That's totally possible. Sorry, there are no real tests or workflow to this app, so stuff is very likely to break :(
