### ISSUE TITLE
Range not working on version 0.1.17?

### ISSUE THREAD

**Issue by andreaslarssen** [seiyria/angular-bootstrap-slider#93]
Hi.

Just updated to version 0.1.17, and even though setting my slider value as an array:

```
<slider ng-model="range" step="1" min="1" max="10" value="[1, 10]"></slider>
```

...I don't get a range slider. 

Is it me or the update?

**Comment by seiyria** [comment]
I have no idea, if you don't provide an example I can't double check either!

**Comment by andreaslarssen** [comment]
Seems like you now need to define range="true". Wasn't needed for the last version I ran. My bad.
