### ISSUE TITLE
Formatter with HTML code and/or Bind

### ISSUE THREAD

**Issue by zauker** [seiyria/angular-bootstrap-slider#97]
Hi all,
one of my need with Angular Bootstrap Slider is have a custom Tooltip.
Formatter works fine but it take only text plain, i'm not able to use an HTML tag or insert a bind of a value in $scope {{}}.
It is possible render HTML code inside Tooltip via formatter attribute?

**Comment by seiyria** [comment]
No. You shouldn't be putting HTML in tooltips anyway, there is not enough space there to justify it. 

Related: https://github.com/seiyria/bootstrap-slider/issues/321

**Comment by zauker** [comment]
If it is possible to add HTML sure i'll could adjust it via CSS.
This is an example:
http://plnkr.co/edit/wumvDyTDAZiG4P2KlsLQ?p=preview

for that example i made a change to _setText function on bootstrap-slider

**Comment by seiyria** [comment]
Yes, we know it's possible, we discourage it. Tooltips are not meant to work like that. If you want that kind of support, it will have to be done entirely by you.

**Comment by klihelp** [comment]
Feature needed in eg. my usecase is to display an image inside the tooltip.
